Last One Please

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -35,10 +35,10 @@ node {
 
     		    echo "Verifying PyInstaller installation..."
     		    ls -la /tmp/pyinstaller/bin
-    		    pyinstaller --version || (echo "PyInstaller not found in PATH!" && exit 1)
+    		    /tmp/pyinstaller/bin/pyinstaller --version || (echo "PyInstaller not found in PATH!" && exit 1)
 
     		    echo "Running PyInstaller..."
-    		    pyinstaller --onefile sources/add2vals.py
+    		    /tmp/pyinstaller/bin/pyinstaller --onefile sources/add2vals.py
 
     		    echo "Checking for dist directory..."
     		    ls -la dist/ || (echo "dist directory not found!" && exit 1)
